@cfc-bundle @provisioning @smoke
Feature: CFC Bundle - Add CFC Bundle during Provisioning
    As a system administrator
    I want to add CFC bundle during Order Provisioning without activating the component
    So that the bundle becomes available for IIDs with major bundles

    Background:
        Given the user is logged into the system
        And the user has access to order provisioning functionality

    @major-bundles @auto-add
    Scenario: Add CFC Bundle automatically for ESO order with major bundles
        Given an ESO order exists without CFC bundle
        And the order contains major bundle "ADP Essential"
        When the order provisioning process executes
        Then CFC bundle should be automatically added for the IID
        And CFC component should be available but not activated
        And the availableBundles property should contain CFC bundle information
        And logs should be generated by CFC component subscriber

    @existing-bundle @validation
    Scenario: Handle ESO order that already contains CFC bundle
        Given an ESO order exists with CFC bundle already included
        And the order contains major bundle "Run Complete and HR"
        When the order provisioning process executes
        Then the system should successfully process the CFC bundle
        And no duplicate bundle entries should be created
        And CFC component should be available but not activated
        And the availableBundles property should be updated correctly

    @context-properties @installation
    Scenario: Verify installation context properties after provisioning
        Given the order provisioning process has completed successfully
        And CFC bundle has been added to the order
        When checking the installation context
        Then the availableBundles property should be present
        And the property should contain CFC bundle information
        And bundles should be in available state not activated state
        And the RequireActivation property should be properly configured

    @task-creation @workflow
    Scenario: Create CFC task when component becomes available
        Given CFC component becomes available after provisioning
        When the system processes the component status change
        Then CFC task should be created in the system
        And the task should be visible in to-do tasks
        And task should indicate component availability status
        And task creation logs should be recorded

    @context-integration @display
    Scenario: Display available bundles in core context wrapper
        Given the system has available bundles including CFC
        When accessing the core context wrapper
        Then available bundles should be displayed correctly
        And CFC bundle should appear in the available bundles list
        And bundle status should show as available not activated

    @system-model @configuration
    Scenario: Verify system model and configuration updates
        Given CFC bundle provisioning has been implemented
        When checking system model properties
        Then new property should be present in system model
        And index_Config file should display available bundles in top.run.context
        And nextgen installation context should include the new property

    @bundle-types @comprehensive
    Scenario Outline: Handle different major bundle combinations
        Given an ESO order contains major bundle "<bundle_type>"
        And the order does not contain CFC bundle
        When the order provisioning process executes
        Then CFC bundle should be automatically added for the IID
        And CFC component should be available but not activated
        And the provisioning should complete successfully

        Examples:
            | bundle_type             |
            | ADP Essential           |
            | Run Complete and HR     |
            | Run Complete and HRPLUS |
            | HR PRO                  |

    @error-handling @negative
    Scenario: Handle provisioning errors gracefully
        Given an ESO order with invalid bundle configuration
        When the order provisioning process encounters an error
        Then the system should handle the error gracefully
        And appropriate error messages should be logged
        And the order status should reflect the error condition
        And no partial bundle additions should occur

    @activation-prevention @validation
    Scenario: Ensure bundle addition does not trigger activation
        Given CFC bundle is being added during provisioning
        When the bundle addition process completes
        Then the component should be in available state only
        And the component should not be in activated state
        And the RequireActivation property should prevent auto-activation
        And component status should be clearly distinguishable
